// Code generated by protoc-gen-go. DO NOT EDIT.
// source: health/health.proto

/*
Package health is a generated protocol buffer package.

It is generated from these files:
	health/health.proto

It has these top-level messages:
	Empty
	HealthReply
*/
package health

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HealthReply_ServingStatus int32

const (
	HealthReply_UNKNOWN     HealthReply_ServingStatus = 0
	HealthReply_SERVING     HealthReply_ServingStatus = 1
	HealthReply_NOT_SERVING HealthReply_ServingStatus = 2
)

var HealthReply_ServingStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "SERVING",
	2: "NOT_SERVING",
}
var HealthReply_ServingStatus_value = map[string]int32{
	"UNKNOWN":     0,
	"SERVING":     1,
	"NOT_SERVING": 2,
}

func (x HealthReply_ServingStatus) String() string {
	return proto.EnumName(HealthReply_ServingStatus_name, int32(x))
}
func (HealthReply_ServingStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type HealthReply struct {
	Status HealthReply_ServingStatus `protobuf:"varint,1,opt,name=status,enum=health.HealthReply_ServingStatus" json:"status,omitempty"`
}

func (m *HealthReply) Reset()                    { *m = HealthReply{} }
func (m *HealthReply) String() string            { return proto.CompactTextString(m) }
func (*HealthReply) ProtoMessage()               {}
func (*HealthReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HealthReply) GetStatus() HealthReply_ServingStatus {
	if m != nil {
		return m.Status
	}
	return HealthReply_UNKNOWN
}

func init() {
	proto.RegisterType((*Empty)(nil), "health.Empty")
	proto.RegisterType((*HealthReply)(nil), "health.HealthReply")
	proto.RegisterEnum("health.HealthReply_ServingStatus", HealthReply_ServingStatus_name, HealthReply_ServingStatus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Health service

type HealthClient interface {
	Check(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthReply, error)
}

type healthClient struct {
	cc *grpc.ClientConn
}

func NewHealthClient(cc *grpc.ClientConn) HealthClient {
	return &healthClient{cc}
}

func (c *healthClient) Check(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthReply, error) {
	out := new(HealthReply)
	err := grpc.Invoke(ctx, "/health.Health/Check", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Health service

type HealthServer interface {
	Check(context.Context, *Empty) (*HealthReply, error)
}

func RegisterHealthServer(s *grpc.Server, srv HealthServer) {
	s.RegisterService(&_Health_serviceDesc, srv)
}

func _Health_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/health.Health/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServer).Check(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Health_serviceDesc = grpc.ServiceDesc{
	ServiceName: "health.Health",
	HandlerType: (*HealthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _Health_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "health/health.proto",
}

func init() { proto.RegisterFile("health/health.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xce, 0x48, 0x4d, 0xcc,
	0x29, 0xc9, 0xd0, 0x87, 0x50, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x6c, 0x10, 0x9e, 0x12,
	0x3b, 0x17, 0xab, 0x6b, 0x6e, 0x41, 0x49, 0xa5, 0x52, 0x0b, 0x23, 0x17, 0xb7, 0x07, 0x58, 0x2c,
	0x28, 0xb5, 0x20, 0xa7, 0x52, 0xc8, 0x92, 0x8b, 0xad, 0xb8, 0x24, 0xb1, 0xa4, 0xb4, 0x58, 0x82,
	0x51, 0x81, 0x51, 0x83, 0xcf, 0x48, 0x51, 0x0f, 0xaa, 0x1f, 0x49, 0x91, 0x5e, 0x70, 0x6a, 0x51,
	0x59, 0x66, 0x5e, 0x7a, 0x30, 0x58, 0x61, 0x10, 0x54, 0x83, 0x92, 0x15, 0x17, 0x2f, 0x8a, 0x84,
	0x10, 0x37, 0x17, 0x7b, 0xa8, 0x9f, 0xb7, 0x9f, 0x7f, 0xb8, 0x9f, 0x00, 0x03, 0x88, 0x13, 0xec,
	0x1a, 0x14, 0xe6, 0xe9, 0xe7, 0x2e, 0xc0, 0x28, 0xc4, 0xcf, 0xc5, 0xed, 0xe7, 0x1f, 0x12, 0x0f,
	0x13, 0x60, 0x32, 0x32, 0xe7, 0x62, 0x83, 0x58, 0x20, 0xa4, 0xcb, 0xc5, 0xea, 0x9c, 0x91, 0x9a,
	0x9c, 0x2d, 0xc4, 0x0b, 0xb3, 0x19, 0xec, 0x50, 0x29, 0x61, 0x2c, 0x0e, 0x51, 0x62, 0x48, 0x62,
	0x03, 0xfb, 0xcb, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x87, 0x6e, 0xe1, 0xf6, 0xee, 0x00, 0x00,
	0x00,
}
